version: '3'
services:
    nginx_web_1:
        container_name: docker_haproxy_NGINX_con_1
        build: ./nginx/web1
        ports:
            - 80
        networks:
            public_net:
                ipv4_address: 172.16.0.10
                aliases: 
                    - nginx1
    nginx_web_2:
        container_name: docker_haproxy_NGINX_con_2
        build: ./nginx/web2
        ports:
            - 80
        networks:
            public_net:
                ipv4_address: 172.16.0.20
                aliases: 
                    - nginx2
    haproxy:
        build: ./haproxy
        ports:
            - 80:80
            - 88:88
        expose:
            - 80
        networks:
            public_net:
                ipv4_address: 172.16.0.2
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.0.0/24
